
export type ProjectStatus = 'prototype' | 'funding' | 'production' | 'early-access' | 'released';

export interface CodeSnapshot {
  id: string;
  timestamp: number;
  code: string;
  label: string; // e.g. "Manual Save", "v1.1"
}

export interface PlayStat {
  time: string; // ISO timestamp or label
  count: number; // Unique players
  timestamp?: number; // Added for tooltips
}

export interface ProjectAsset {
  id: string;
  name: string;
  mimeType: string;
  data: string; // base64
  type: 'image' | 'audio' | 'video';
  coverUrl?: string; // NEW: For audio cover art persistence
}

export interface GameVersion {
  id: string;
  timestamp: number;
  prompt: string;
  code: string; // The base code generated by AI
  versionNumber: number;
  summary?: string; 
  shortTitle?: string; // NEW: AI generated short title for the version
  modelName?: string; // NEW: The AI model used to generate this version
  
  // Metadata Snapshot
  description?: string;
  instructions?: string;
  
  // Sub-version control
  minorVersions?: CodeSnapshot[]; 
  activeMinorVersionId?: string; // Which sub-version is currently active/displayed
}

export interface GameResolution {
  width: number;
  height: number;
  mode: 'responsive' | 'fixed';
}

export interface Game {
  id: string;
  title: string;
  description: string;
  instructions: string;
  author: string;
  authorId?: string; // NEW: DB User ID for linking to profile
  likes: number; // Represents general popularity
  shares?: number; // NEW: Share count
  commentCount?: number; // NEW: Real discussion count
  collections?: number; // NEW: Count of how many users collected this
  coins: number; // Represents "Sponsorship/Funding"
  fundingGoal: number; // Target to reach next stage
  status: ProjectStatus;
  code: string;
  thumbnailUrl?: string;
  type: 'white-box' | 'polished';
  createdAt: number;
  
  // Relationship
  forkedFromId?: string; // The ID of the parent game this was forked from
  
  // Project Assets
  assets?: ProjectAsset[];

  // Viewport Settings
  resolution?: GameResolution; // Working/Studio resolution
  
  // AI Autoplay Configuration (Attract Mode)
  autoplayScript?: string; 
  isAgentActive?: boolean; // NEW: Toggle state independent of script existence
  
  // AI Agent Version History
  agentHistory?: CodeSnapshot[]; // NEW: Persisted history for the agent script

  // Visibility Control
  isPublished?: boolean;
  publishedCode?: string; // The code that is actually live/visible to others
  publishedVersionId?: string; // The ID of the version that is live
  publishedMinorVersionId?: string; // The ID of the specific minor version (snapshot) that is live
  publishedResolution?: GameResolution; // The resolution configuration for the live version
  versionLabel?: string; // NEW: Manual version string (e.g. "1.0", "1.1-beta")

  // Analytics (Real Data)
  playCount?: number;      // Total times played/viewed
  totalPlayTime?: number;  // Total seconds played by all users
  followersGained?: number; // Count of follows originating from this game context

  // Simulated project data
  teamMembers?: number;
  tasksCompleted?: number;
  totalTasks?: number;
  
  // Version Control
  history?: GameVersion[];
  currentVersionIndex?: number;
  modelName?: string; // NEW: The AI model used for the current state
}

export interface SocialStats {
  followers: number;
  following: number;
  totalLikes: number;
  isFollowing?: boolean;
}

export interface Asset {
  id: string;
  name: string;
  type: 'model' | 'sprite' | 'audio' | 'script' | 'ui';
  price: number;
  author: string;
  authorId?: string; // NEW: To distinguish "Uploaded by Me"
  authorAvatar?: string; // NEW: To display real author avatar
  imageUrl: string;
  coverUrl?: string; // NEW: For audio cover art
  tags?: string[]; // NEW: Tags for search and discovery
  salesCount?: number; // NEW: Total purchases
  description?: string; // NEW: For Asset Details page
  commercialUse?: boolean; // NEW: License flag
  allowRemix?: boolean; // NEW: Remix License flag
  viewCount?: number; // NEW: For Asset Details page
  createdAt?: number; // NEW: Timestamp
  likeCount?: number; // NEW: Real like count
  fileSize?: number; // NEW: File size in bytes
}

export interface UserPrivacy {
  publicCollection: boolean;
  publicFollowers: boolean;
  publicFollowing: boolean;
}

export interface PortfolioCategory {
  id: string;
  name: string;
  assetIds: string[];
}

export interface User {
  id: string;
  handle: string; // e.g. @developer
  displayName: string;
  avatarUrl?: string; // optional
  coins: number;
  level: number;
  isPro: boolean;
  isCreator?: boolean; // NEW: Contracted Creator Status
  joinedAt: number;
  email?: string;
  // NEW FIELDS
  bio?: string;
  shortId?: string; // The public facing UID (e.g. 1002345)
  privacy?: UserPrivacy; // Privacy settings
  acceptsCommissions?: boolean; // New: For Creator Profile
  commissionRate?: string; // New: "Starts at 500"
  portfolioSettings?: PortfolioCategory[]; // NEW: Custom asset categories
  inventorySettings?: PortfolioCategory[]; // NEW: Custom inventory categories
  favoritesSettings?: PortfolioCategory[]; // NEW: Custom favorites categories
}

export interface Comment {
  id: string;
  gameId: string;
  authorId: string;
  authorName: string;
  authorAvatar?: string;
  content: string;
  likes: number;
  timestamp: number;
  parentId?: string; // NULL if root comment, ID if reply
  isPinned?: boolean; // NEW: Supports author pinning
}

export enum TabView {
  FEED = 'FEED',       // Player Hub: Discovery
  MARKET = 'MARKET',   // Asset Store
  CREATE = 'CREATE',   // AI Generator (The "+" button)
  STUDIO = 'STUDIO',   // Project Management (Left of Me)
  PROFILE = 'PROFILE'  // User Profile
}

export interface GenerationConfig {
  prompt: string;
  complexity: 'simple' | 'complex';
}

export interface Notification {
  id: string;
  type: 'system' | 'like' | 'comment' | 'fork' | 'release' | 'update';
  title: string;
  message: string;
  timestamp: number;
  isRead: boolean;
  data?: any;
}

export interface ChatMessage {
  id: string;
  senderId: string;
  text: string;
  timestamp: number;
  isRead?: boolean;
}

export interface ChatConversation {
  id: string;
  userId: string; // The other user's ID
  userName: string;
  userAvatar?: string;
  lastMessage: string;
  lastTimestamp: number;
  unreadCount: number;
  messages?: ChatMessage[]; // Optional, fetched on demand
}

// NEW: Report Types
export type ReportReason = 'spam' | 'abuse' | 'copyright' | 'other';
export type ReportTargetType = 'game' | 'user' | 'comment' | 'asset';
